package Entities.Framework.StateMachine;

// State flags
public enum StateTag {
	INACTABLE, DASHABLE, MOVE_CANCELLABLE, MOVEABLE, KNOCKED, JUMPABLE, CAN_MELEE, CAN_FIRE, INVULNERABLE, IDLE, ACCEL,
	MOVING, DASHING, DASH_ATK, JAB1, JAB2, LUNGE, TUMBLE, WINDUP, FIRE, WINDOWN;
}